# Generated by Django 5.0.6 on 2026-05-08 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public-safe identifier — never exposes sequential DB row IDs.', primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('xml_context', models.TextField(blank=True, help_text='DTD-validated XML context sent to Gemini (populated by worker).')),
                ('video_blueprint', models.JSONField(blank=True, help_text='Structured JSON plan returned by Gemini (script, shot list, etc.).', null=True)),
                ('video_result_url', models.URLField(blank=True, help_text='Final rendered video URL (populated after FFmpeg stitching).', null=True)),
                ('error_log', models.TextField(blank=True, help_text='Full traceback or Celery retry history on failure.', null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for external status polling.', max_length=255, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Job',
                'verbose_name_plural': 'Video Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
