# Generated by Django 5.0.6 on 2026-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='blueprint_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='generation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='orchestration_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='total_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
